version: "3.3"
services:
  backend:
    build:
      context: ./backend
    image: anemone:backend
    ports:
      - 8080:8080
    volumes:
      - ./backend/:/app
    command: ["--module", "anemone.wsgi:application", "--http", "0:8080","--processes", "4", "--py-autoreload", "1"]
  front:
    build:
      context: ./front
    image: anemone:front
    ports:
      - 3000:3000
    volumes:
      - ./front:/opt/app
  nginx:
    image: nginx
    volumes:
      - ./nginx:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
