version: "3.3"
services:
  postgresql:
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: anemone
      POSTGRES_USER: anemone
      POSTGRES_DB: anemone
  backend:
    build:
      context: ./backend
    image: anemone:backend
    ports:
      - 8080:8080
    volumes:
      - ./backend/:/app
    command: ["--module", "anemone.wsgi:application", "--http", "0:8080","--processes", "4", "--py-autoreload", "1"]
  front:
    build:
      context: ./front
    image: anemone:front
    ports:
      - 3000:3000
    volumes:
      - ./front:/opt/app
  nginx:
    image: nginx:1.17.1-alpine
    volumes:
      - ./nginx:/var/www
      - ./backend/media:/images
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
volumes:
  pgdata: {}
